tmewett/BrogueCE

CHANGELOG.md
src/brogue/IO.c
src/brogue/Recordings.c
src/brogue/Rogue.h

playback for a long period.
This can be demonstrated by clicking left mouse about 20 times in one place during playback. The playback pauses for a long time as brogue runs through the clicks, pausing for no reason between processing each click even though it doesn't do anything.

Fix an issue whereby too much user input during playback can pause the

---

CHANGELOG.md

The charm changes in 1.7.5-flend1 restore all charms to v1.7.4 behaviour
where the charms were affected by bugs introduced during the change to
fixed point in v1.7.5. There were no intended charm changes according to
the v1.7.5 changelog and it was clear the changes were due to bugs (and
unbalanced the game in many cases). The charms now behave as in v1.7.4
although there are some off-by-1 changes that are not obviously bugs,
just side effects of the new maths.

Moved charm change to Bug fixes in Changelog

---

Makefile
src/brogue/Architect.c
src/brogue/Buttons.c
src/brogue/Globals.c
src/brogue/IO.c
src/brogue/Items.c
src/brogue/Math.c
src/brogue/Monsters.c
src/brogue/Movement.c
src/brogue/Recordings.c
src/platform/platformdependent.c

What's **not** done:
* warning: ISO C forbids an empty translation unit [-Wpedantic]
* warning: passing argument 1 to restrict-qualified parameter aliases with argument 3 [-Wrestrict] (sprintf)
* warning: address of array 'newItem->inscription' will always evaluate to 'true' [-Wpointer-bool-conversion]

Fixed code to get rid of some compile time warnings

---

src/brogue/Items.c

Those warnings worded differently on different compilers, but they all
boil down to the fact that the same source and target is used in a
sprintf. This commit makes sure, that these are being written via an
intermediate buffer. It also might have fix a bug discussed on discord
as Tom believes that the bug is a manifestation of this issue

Fix sprintf warnings

---

changes/confirm-target-with-numpad5.md
src/brogue/Items.c

This change means the right hand does not need to leave the numpad when targetting. 
Numpad 5 is rest when not targetting and has no other existing function when targetting.
The change is also useful for web-brogue since web-brogue supports a d-pad that simulates the numpad.

Allowing numpad 5 (center) to confirm target

---

changes/mage-class-update.md
src/brogue/Globals.c

Dar Priestesses weren't included under mages in monster class
Editted monsterClassCatalog to fix that
I checked with seed 2170 that the item description is displaying correctly:
Let me know if I need to do anything else, I'm a little rusty on git, and super experienced with it to begin with.

Add dar priestess to mage class

---

changes/fix-alt-enter-fullscreen.md
src/platform/sdl2-platform.c

Using Alt + Enter for fullscreen used to affect gameplay; it no longer does.

Prevent Alt + Enter fullscreen from affecting game

---

Makefile
changes/allow-recording-switch-to-play.md
src/brogue/IO.c
src/brogue/MainMenu.c
src/brogue/Recordings.c
src/brogue/Rogue.h

If DEBUG is defined in config.mk, pressing 'P' during a recording
hands control over to the player indefinitely, allowing for more
extensive debugging. Switching conserves the old recording, and creates
a new one from the player's inputs.

Allow taking control of the player during playback

---

src/platform/main.c

VS Code complains that `cursesConsole` struct is undefined when none of the three platform symbols is defined.
The error has no effect in practice because the game is always compiled with exactly 1 symbol defined (it wouldn't compile otherwise) but the VS Code highlight is annoying.

Use platform directives consistently

---

src/brogue/Math.c
src/brogue/Recordings.c
src/brogue/Rogue.h

On some architectures, `int` type is 16 bits (C99's minimum requirement).
Because it cannot store numbers higher than 32767, wraparound issues arise related to:
- keyboard commands, like `UP_ARROW` (63232)
- `rand_range()` is called with numbers as high as 60000
For those, use `long` instead.
Related to issue #4.

Fix integer portability

---

changes/64-bit-seeds.md
src/brogue/Globals.c
src/brogue/IO.c
src/brogue/IncludeGlobals.h
src/brogue/MainMenu.c
src/brogue/Math.c
src/brogue/Recordings.c
src/brogue/Rogue.h
src/brogue/RogueMain.c
src/platform/main.c
src/platform/platformdependent.c

Also fixes a bug related to level seeds: each level had 1 in 100,000,000 chance of being non-deterministic (level seed = 0), i.e different on every play or recording replay.
Seeds up to 2^32-1 generate the same dungeons as prior versions.
Recordings are not backward compatible, as the header has increased in size to store the now larger seed.

Extend seeding to 64 bits

---

src/brogue/Architect.c

According to `-fstack-usage` feature, `buildAMachine()` consumed 202336 bytes on the stack. Since it is called recursively, stack could sometimes run out. This non-functional patch moves its largest variables to the heap, to bring its footprint down to only 480 bytes.
On Linux, it can be tested with `ulimit -s 512` (sets stack size to 512 KB) which makes it easy to hit stack limit at low depths.
Fixes #122.

Reduce stack usage

---

changes/fix-input-during-replay.md
src/platform/sdl2-platform.c

While playing a recording, if you hit space during combat (which lasts 0.5 second) the game freezes, but resumes as soon as you move the mouse; the game does not print "Recording paused" either. This issue affects the SDL2 platform only.
Cause: The keypress event is detected and saved into `lastEvent` variable, but gets overwritten before it is processed. The event that gets processed is whichever event follows it (usually a mouse move) once there is one.
Solution: Check if we already have a valid, pending event in `lastEvent`. If so, process it instead of polling for a new one. (Note that `lastEvent` is reset to `EVENT_ERROR` when `_nextKeyOrMouseEvent` returns it, so there is no risk of processing the same event twice.)
Fixes #42.

Fix pause during replay

---

changes/handle-G-keypress-in-playback.md
src/brogue/Recordings.c

Unlike in play mode, during playback you could only enable tiles with the mouse, not with the keyboard.

Handle 'G' keypress during playback

---

changes/enhanced-seed-catalog.md
src/brogue/Items.c
src/brogue/MainMenu.c
src/brogue/Monsters.c
src/brogue/Rogue.h
src/platform/main.c

Add items carried by monsters, shackled vs. caged status for captive 
monsters, and which vault a key will open. Aggregate gold per level. 
Remove the extraneous '+0' from non-enchanted weapons. Remove the 
rating and strength requirement from armor. Add legendary allies 
and both resurrection and commutation altars. Rename 
operations/variables from scum to seed catalog.

Enhance the seed catalog

---

src/brogue/Combat.c
src/brogue/Monsters.c
src/brogue/PowerTables.c

All the crashes I ever got were due to the array out-of-bound errors fixed in this patch.
Also, for consistency with the other functions, pass a `fixpt` to `defenseFraction()`, not a `short`.

Fix array out-of-bound errors

---

changes/fix-offlevel-monster-pathing.md
src/brogue/Architect.c
src/brogue/Rogue.h
src/brogue/RogueMain.c
src/brogue/Time.c

Make sure enemies pathing towards stairs or a pit from the previous level path towards the right tile at the right speed. Previously, mapToPit used the wrong coordinates and mapToStairs mapped to the player's coordinates from the previous level. Also prevents monsters from walking onto each other when the player comes back to a level, which permanently screws up the existing monster.

Fix issues with off-level monster pathing

---

src/brogue/IO.c

70% of the runtime was spent in 1 function, `refreshSideBar`. This patch reorders some instructions to get the same result but with much less computation.
Before:
```
%   cumulative   self              self     total
time   seconds   seconds    calls  ms/call  ms/call  name
70.14      1.01     1.01     1657     0.61     0.62  refreshSideBar
7.64      1.12     0.11  1879853     0.00     0.00  fp_sqrt
```
After:
```
%   cumulative   self              self     total
time   seconds   seconds    calls  ms/call  ms/call  name
29.20      0.33     0.33 15365339     0.00     0.00  fp_sqrt
14.16      0.49     0.16     6257     0.03     0.03  refreshSideBar
```

Reduce CPU usage

---

src/brogue/Monsters.c

When a monster is demoted, we are assigning a new (or no) leader to the monsters on the same level but not to those on other levels. When the monster dies, its memory is freed. Its former followers now hold pointers to freed (and possibly reassigned) memory. This wasn't usually causing a crash, but it was making the game state dependent on `malloc`'s memory management, which isn't good.
This patch checks all levels, to correctly clean up all `leader` pointers.
One of the games on WebRogue's top list was affected by it, resulting in OOS. Possibly many other games that go OOS have the same root cause.
Submitting the patch to `master`, not `release`, because it breaks recordings made with Brogue CE 1.9, which unintentionally *relies* on pointers pointing to the same invalid memory addresses …

Fix invalid pointers to freed memory

---

changes/fix-crash-on-monster-death.md
src/brogue/Combat.c

Buffer sizes in brogue are rather inconsistently set (e.g. use of COLS vs DCOLS for buffer sizes) and we should use snprintf throughout.

Fix a crash where monster death messages could overflow a buffer

---

changes/recording-fixes.md
src/brogue/IO.c
src/brogue/MainMenu.c
src/brogue/Recordings.c
src/brogue/Rogue.h

- Made the loading bars show up on screen by calling pauseBrogue(0) instead of commitDraws. Seems like pauseBrogue and nextBrogueEvent are the only functions that flush the display to screen
- Allow the user to click X or cancel loading while a saved game is loading
- The '6' key now enters a turn number; it used to act like the right arrow
- Turn numbers can now be entered during OOS replays; they used to do nothing

Various recording fixes

---

changes/dont-leak-zap-names-on-reflect.md
src/brogue/Items.c

fixes #115 
Here's an example, where rats are reflective. On first use it's referred to as a bolt, on second use it's identified as flame. Also, poor me, and poor rats.

Don't leak the identity of a wand or staff in the combat message for reflection

---

src/brogue/Recordings.c

The OOS message was shown underneath the player, and sometimes monsters.
Before patch -- cf. `recorded ga@e` on the second line:
After patch:

Fix OOS message polluted by player/monsters

---

src/brogue/Time.c

Burnt item wasn't `free`'d.
Fixes most memory leaks reported by @flend

Fix memory leak in burnItem()

---

src/brogue/IO.c
src/brogue/Items.c
src/brogue/Recordings.c
src/brogue/Rogue.h

When compiling Brogue CE with Visual Studio 2019 Community Edition, at warning level `/W2`, the compiler detects a few issues:
- several unintended or unnecessary conversions from/to `double`
- `%i` was used in two places for `long long int` values
- `HELP_KEY` conflicts with a symbol from the Win32 API

Fix warnings reported by Visual Studio

---

changes/bugfix-grappling-salamander.md
src/brogue/Combat.c
src/brogue/Rogue.h

Fixed a bug where the message "<monster> seizes your legs!" was displayed in error. The message occurred when attacked by a non-adjacent grappling salamander. The player was still free to move, since seizing only takes effect when the monster is adjacent.

"<monster> seizes your legs!" displayed in error

---

src/brogue/Rogue.h

printSeedCatalog has two type-conflicting declarations. Based on use of the function, the correct type is uint64_t. Using clang on OpenBSD I had the error below while compiling. With the fix the game compiled and worked fine on OpenBSD. Thanks for your work on making Brogue more portable!
src/brogue/SeedCatalog.c:217:6: error: conflicting types for 'printSeedCatalog'                                                                    
void printSeedCatalog(uint64_t startingSeed, uint64_t numberOfSeedsToScan, unsigned int scanThroughDepth,                                          
^                                                                                                                                             
src/brogue/Rogue.h:3185:10: note: previous declaration is here …

fix conflicting types uint64_t and unsigned long for printSeedCatalog

---

src/platform/curses-platform.c

`make TERMINAL=YES`:
src/platform/curses-platform.c: In function ‘getTime’:
src/platform/curses-platform.c:113:5: warning: ‘ftime’ is deprecated [-Wdeprecated-declarations]
`man ftime`:
4.2BSD, POSIX.1-2001.  POSIX.1-2008 removes the specification of ftime().
This function is obsolete.  Don't use it.  If the time in seconds
suffices, time(2) can be used; gettimeofday(2) gives microseconds;
clock_gettime(2) gives nanoseconds but is not as widely available.

Get rid of deprecated function ftime()

---

changes/pause-playback-with-mouse-or-Esc.md
src/brogue/Recordings.c

Playback could be un-paused with the mouse, but not paused. This patch allows pausing by clicking anywhere in the window where it previously had no effect. The Escape key now also pauses playback, as it is the key's customary purpose.

Allow pausing playback with mouse or Escape key

---

Makefile
src/brogue/Architect.c
src/brogue/IO.c

Suppresses two bogus gcc warnings in debug mode, and adds the `-Og` flag for better gdb support. From gcc's documentation:
> If you are not using some other optimization option, consider using -Og (see Optimize Options) with -g. With no -O option at all, some compiler passes that collect information useful for debugging do not run at all, so that -Og may result in a better debugging experience.

Debug mode tweaks

---

src/brogue/Light.c

It was originally between 35 and 100%. When the code switched to fixed-point arithmetic, the "35" was accidentally treated as a `fixpt` value, which turns it into 0.000534%. The range effectively became 0 to 65%.

Fix radialFadeToPercent calculation

---

changes/autoidentify-wand-of-invisibility-if-telepathic.md
src/brogue/Items.c

If an unidentified wand of invisibility turns a visible enemy invisible, they become displayed as a 'psychic emanation,' which is an indicator that they're now invisible, not teleported away. This disambiguates the signature of a wand of invisibility from any other potential wand, so the wand can be identified.
There might be a need for some additional text, like
```
You sense a psychic emanation where the <monster> once was.
(Your <wand> must be a wand of invisibility.)
```
I can add that if desired

Autoidentify wands of invisibility if used on an enemy while telepathic

---

changes/fix-entrance-crashes.md
src/brogue/Movement.c
src/brogue/Rogue.h

moveEntrancedMonsters didn't account for a monster dying in the middle of the turn. If an entranced monster moves and the next monster in the chain dies, the rest of the function will iterate across the rest of the dead monsters from that turn, potentially moving an already dead monster and causing crashes.
This code makes the loop similar to what happens in regular monster movement. It restarts every time an entranced monster moves and uses a new bookkeeping flag to keep track of who has already moved.

Fix a crash from moving entranced monsters

---

changes/replay-goto-previous-level.md
src/brogue/IO.c
src/brogue/Recordings.c

I think persisting the first arrival turn for each level is viable, but this PR doesn't use that approach and consequently there is some duplicated logic with advanceToLocation. I didn't see an obvious way to share the logic other than creating a half-dozen small functions. I ended up just creating one for playbackReset. With persisted turns, advanceToLocation would handle all navigation.
I think a neat way to persist would be a linked list of depth changes. In fact, it might be useful to add "next/previous Depth Change" navigation options. Having said, the current PR gets the job done. :-)

Add "go to previous level" key to replay viewer (#55)

---

changes/negate-mutation.md
src/brogue/Globals.c
src/brogue/Items.c
src/brogue/Rogue.h

When a mutated monster is negated, remove the mutation so it doesn't show in the sidebar (closes #182)

When a mutated monster is negated, remove the mutation

---

changes/fix-close-window-button.md
src/brogue/MainMenu.c
src/brogue/Recordings.c
src/brogue/Rogue.h
src/brogue/RogueMain.c
src/platform/sdl2-platform.c

The window now closes immediately on the first click of the `[x]` button, no matter what the situation is (play, auto-play, recording playback, text input, message acknowledgement...)
The game (or recording) is automatically and fully saved. Previously, closing the window while a game was in progress did not flush the buffer to file, so the savegame could be missing several turns.
Closing the window after the game is over (e.g at message "You died") automatically saves the recording.
Fixes #54.

Fix unresponsive window close button

---

changes/fix-explosion-on-fall.md
src/brogue/Combat.c
src/brogue/Time.c

Fixed a bug where monsters would explode before their fall if they die to fall damage. Lost a few runs to this...
Also affects infested monsters.

Monsters don't explode when falling to their death

---

changes/monkey-lava.md
src/brogue/Monsters.c
src/brogue/RogueMain.c

Originally, monsters that begin fleeing outside player view use the last safety map generated, which doesn't apply to the monster and could be from several floors prior. This is why monkeys in key holders would occasonally jump into lava. Aside from updating the safety map properly, the rest of the code makes sure monkeys/imps on the altars stay still until the player sees them.

Make monsters flee properly outside player view

---

src/brogue/Recordings.c
src/brogue/Rogue.h

When loading a savegame made with an earlier version, then saving it again, the new savegame may go out-of-sync because the header contains the new version number but the first turns still need the old version to be applied correctly.
This patch ensures the header contains the version that the game was started with.

Preserve patchVersion from reloaded game

---

changes/include-seed-in-filenames.md
src/brogue/Recordings.c

Includes the seed number, depth, mode and situation in default save/recording file names. Players who don't care to edit them will find it easier to browse their list of recordings or saved games.
This patch is forward-compatible with 64-bit seeds. If the seed is very long it gets shortened, to keep a reasonable file name length.

Include seed and depth in default save/recording file names

---

Makefile
config.mk
src/brogue/Rogue.h
tools/git-extra-version

If a build is made by CI (has $CI defined) and a tag pointed at its git commit, call it a release build.  Call other builds unstable builds.
Put the git commit and branch name on the title screen and --version output of all unstable builds.  If built locally use "unstable" instead of a commit hash or branch, since the work tree might not be clean.
We avoid calling git directly since it may not be available.  Instead only variables supplied by the CI environment are used.

Show git commit and branch name in unstable builds

---

src/platform/tiles.c

`SDL_CreateRGBSurfaceWithFormat` was first introduced in SDL 2.0.5.
Also fixes two typos.

Polyfill for SDL_CreateRGBSurfaceWithFormat

---

changes/fix-offlevel-monster-pathing.md
src/brogue/Architect.c
src/brogue/Rogue.h
src/brogue/RogueMain.c
src/brogue/Time.c

Patch versioned fix of the monster pathing bug. Who knows when 1.10 will come out, but this works for now.
As a side note, unfortunately you can't use patch version on an enum, so I had to change the 2 instances of PERMANENT_TILE_FLAGS instead, and it has to be referenced this way if it's ever added again between now and 1.10.

Monster pathing fix with patch version

---

changes/fix-discordant-snipers.md
src/brogue/Monsters.c

This applies to all ranged casters, including dragons.

Discordant wandering monsters now respect stealth range (#217)

---

changes/pit-bloat-crashes.md
src/brogue/Time.c

There were 2 types of crashes:
- memory access when a pit bloat dies in an explosion, and
- an infinite loop when the player is levitating in burning gas and a pit bloat dies near the player (unclear on exact conditions).
The explosion issue happens because the pit bloat's hole replaces the explosion and the game is unable to find the explosive layer that it assumes exists when printing out the pit bloat's death message.
For the loop: when exposeTileToFire clears gas, it sets the gas volume to 0 but leaves 'layers[GAS]' untouched. Clearing the gas layer makes gas burn [awkwardly](https://cdn.discordapp.com/attachments/647802299783184384/799503542430859294/Screenshot.png) and the layer is cleared when gases are updated anyways, so I left the behavior intact. Instead, I cut off the loop …

Fix pit bloat gas crashes

---

changes/monst-detail.md
src/brogue/Monsters.c

Originally, if your weapon was un-ID'd, the combat info from hovering over a monster wouldn't account for strength in your average damage. An un-ID'd broadsword would be displayed as doing 100% average to a vampire bat regardless of strength.
The new code is written the same way as in recalculateEquipmentBonuses from Items.c

Fix player damage for un-ID'd weapons in monster infobox

---

src/platform/main.c
src/platform/sdl2-platform.c
src/platform/tiles.c

Previously it used a 70% screen fit on both width and height, or 16:9 aspect
when using `--size`, however these lead to a slightly wider window than in the
past.
cc @AntonyBoucher for review

Start game with fixed aspect ratio

---

changes/fix-lich-polymorph-crash.md
src/brogue/Items.c

Game was crashing in `freeCreature` after call to `emptyGraveyard`. It seems the polymorph code handling the special case of liches/phoenixes was needlessly calling `kill ` for the phylactery/egg (carriedMonster), which adds the creature to the graveyard.

Fix game crash when polymorphing a lich or phoenix (#238)

---

changes/ultra-wide-monitor-support.md
src/platform/tiles.c

For lucky owners of ultra-wide monitors (aspect ratio > 2:1) Brogue opens by default with a window that is taller than the monitor. This patch ensures that the default window size does not exceed 70% of monitor's width nor 70% of monitor's height. Initial window aspect ratio is 16:10.

Better default window size for wide screens

---

changes/dungeon-generation-on-arm.md
src/brogue/Dijkstra.c

Unlike other numeric types, `char` apparently is not implicitly `signed char`, but rather has an unspecified signed-ness (see [0]).  Since negative guards are used, and since it is the default on my x86 gcc, use a signed char.
[0]: https://stackoverflow.com/a/2054941/580412
Closes #68

Explicitly sign char used as cost intermediate

---

changes/truecolor-terminal.md
src/platform/term.c

Many terminals now accept 24-bit colors for foreground and background, removing the 256-color palette constraint.
Truecolor terminal support is detected more or less reliably (there is no standard method yet) by reading the $COLORTERM environment variable, which is conventionally set to 'truecolor' or '24bit' by those terminals.
Ncurses started supporting truecolor mode in version 6.1 (January 2018) but to make it work with older versions, this patch rolls out its own implementation with a couple of ANSI escape sequences.
To learn more see [color escape sequences](https://stackoverflow.com/questions/4842424/list-of-ansi-color-escape-sequences) and [true color terminals](https://gist.github.com/XVilka/8346728).

Add truecolor terminal output

---

changes/negation-wand-auto-id.md
src/brogue/Items.c
src/brogue/Rogue.h

Wands of negation auto-ID if the bolt has an effect. A combat message is shown for any monster affected by negation.

Auto-ID wand of negation if monster description changes (#233)

---

changes/summon-minions-without-items.md
src/brogue/Monsters.c

Partial resolution of issue #251.
This fixes a bug where summoned minions could spawn with a carried item which was then deleted, making it unavailable for 
future monster drops and leading to differences in available items for players playing the same seed.

Summon minions without items (#251)

---

changes/negated-status.md
src/brogue/Globals.c
src/brogue/IO.c
src/brogue/IncludeGlobals.h
src/brogue/Items.c
src/brogue/Monsters.c
src/brogue/Rogue.h

Add text to the sidebar and monster details to show that a monster was affected by negation

Display "negated" in the sidebar and monster details

---

src/platform/tiles.c

- Detect and report when the binary is started from the wrong directory.
- Ensure the glyph optimization window opens and can be closed.
- Report when tiles.bin cannot be written.

Fix MAC_APP=YES accidentally made mandatory on mac

---

changes/hybrid-graphics-mode.md
src/brogue/IO.c
src/brogue/Recordings.c
src/brogue/Rogue.h
src/platform/main.c
src/platform/platform.h
src/platform/platformdependent.c
src/platform/sdl2-platform.c

Implements one of Pender's suggestions, to have a good looking dungeon with easily recognizable creatures.
It adds a third graphics mode, also toggled with the G key.
- Text: Unicode only
- Tiles: tiles for everything (environment, monsters, items)
- Hybrid: tiles for environment, text for monsters and items
Based on master, in case this change affects web-brogue.

Hybrid graphics

---

src/brogue/Rogue.h
src/platform/main.c

Brogue won't compile if some macros are not defined. This patch makes it compile by defaulting macros to sane values (with warning for one of them).

Guard again undefined macros

---

changes/assisted-aiming.md
src/brogue/Items.c
src/brogue/Monsters.c
src/brogue/Movement.c
src/brogue/Rogue.h

Casting bolts and throwing items happen in a straight line as always, but now the pathing algorithm can aim for a point that is not the exact center of the target cell, to improve the outcome. Tunneling will try to hit as many walls as possible, throwing objects will try to avoid them. Bolts will try to hit many enemies and few allies, or vice versa depending on the type of bolt. If a bolt can only hit 1 creature, Brogue will favor hitting the targeted one over any other. If firebolt can hit as many enemies with or without setting terrain on fire, it will prefer not to.
This makes it unnecessary to aim for a cell beyond your intended target, trying to trick the Bresenham algorithm into passing through the cells you want.
The projectile is still thrown from the exact center of the origin …

Auto-kink throw trajectories

---

src/brogue/Architect.c
src/brogue/Combat.c
src/brogue/Items.c
src/brogue/Monsters.c
src/brogue/Movement.c
src/brogue/Recordings.c
src/brogue/Rogue.h
src/brogue/RogueMain.c
src/brogue/Time.c
src/platform/main.c

Right now, the `master` branch still carries the version number `1.9.4`. This is problematic because any build made off `master` will show "1.9.4" in the main menu, which is misleading, as recordings made with `master` builds are not backward compatible with 1.9.4 builds. We cannot safely change it to `1.10.0` though, because doing so will disable features introduced since 1.9.1, and restore bugs fixed since 1.9.1, due to the dozens of `patchVersion` checks which have not yet been removed from the code merged into `master`.
Removing the `patchVersion` checks in master is simple (turn the comparisons into either `true` or `false`, then simplify the code) but it causes annoying merge conflicts which we would rather not deal with on an ongoing basis.
This patch offers a solution, so that we …

Portable patchVersion checks

---

src/brogue/Architect.c

Closes #260
Two longstanding bugs fixed here:
- Any machine that calls expandMachineInterior() would eliminate all doors and secret doors on the entire depth (!!!)
- Rarely addLoops() could place a door immediately adjacent to an existing door
This is a new PR that rebases [PR 275](https://github.com/tmewett/BrogueCE/pull/275), which got snarled up by my slow climb up the github learning curve... I will close that PR in favor of this one.

Fix two levelgen door bugs

---

src/brogue/Architect.c

Fixes a remaining issue [spotted](https://github.com/tmewett/BrogueCE/pull/289#issuecomment-812806171) by @withinwheels caused by [this prior levelgen door bugfix PR](https://github.com/tmewett/BrogueCE/pull/289).
After expanding the interior of a machine, we take one last pass through the depth and delete any doors or secret doors that remain in the machine's interior.
In hindsight, this is what the original code was intended to do, but it was situated in the wrong place in the loop, so it inadvertently applied to the entire depth rather than just the machine's interior.
Screenshot of fixed level generation (compare to screenshots in @withinwheels 's comment linked above):

Remaining levelgen door bugfix

---

src/brogue/Time.c

The purpose of the `MB_ALREADY_SEEN` monster flag is to interrupt compound movements (exploration). It does not get set during recording playback, so internal game state should not depend on it, lest we get OOS errors during playback.
Yet this was happening when a monster that _was_ seen while exploring/auto-playing showed up through a hidden door: the door was not getting revealed then (because `MB_ALREADY_SEEN` was set), but it was revealed during playback (`MB_ALREADY_SEEN` not set). The OOS occurred soon after, as the `rand_percent()` call in `search()` function depends on door secrecy.
This patch fixes the erroneous dependency in Brogue 1.9.4 and above. The dependency also affected runic weapon/armor's flags, although much less frequently than secret doors.

Fix secret door OOS

---

changes/equipment-hot-swap.md
src/brogue/Combat.c
src/brogue/IO.c
src/brogue/Items.c
src/brogue/Rogue.h
src/brogue/RogueMain.c

Whenever a piece of equipment displaces another when being equipped, it
is "swapped in" and the other is "swapped out".  Pressing "w" then
exchanges these two as a player action.  In this way players can
"juggle" rings, weapons or armor with a single key stroke.
If either of the swapped in or out items leaves the pack, the swapped
in/out status of both is cleared.  There is no visual feedback (in the
inventory screen or elsewhere) of which items are swapped in or out.
Closes #220

Press w to hot-swap equipment

---

src/brogue/Globals.c
src/brogue/Time.c

When something is consumed by lava or similar, look at the tile
description and strip off any leading "a " or "an ".  This allows us to
have "a sacrificial pit" tiles, but still talk about "the sacrificial
pit".
A few other small edits are included as well.
Closes #281

Fix a few grammatical nits with sacrificial altars

---

src/brogue/Items.c

..regardless if their kind is known or not.  The actual game behavior already reflects this (see `effectiveRingEnchant`), this commit just fixes the incorrect item description.
closes #227

Identified rings function at their enchantment

---

.gitignore

Use two asterisks to ignore them regardless of the subdirectory they are in.
Also add **.desktop files to .gitignore.
Closes #303.

Add all unusable IDE/compiler files to .gitignore

---

src/brogue/Architect.c
src/brogue/Movement.c
src/brogue/Recordings.c
src/brogue/Rogue.h

Fixes #302.
Movement's keystroke is now recorded up-front at the beginning of `playerMoves()`, in case `gameOver()` is called and the recording saved before we exit the function. If the movement is cancelled, the keystroke is removed from the buffer with a new function, `cancelKeystroke()`. There is no risk of having the buffer flushed between `recordKeystroke` and `cancelKeystroke` because this only happens at the end of the turn (by `RNGCheck` in `playerTurnEnded`) or when the game is over, after which the player cannot cancel anything.
(`brogueAssert(!p->occupied[i][j] ...` is to fix a broken assert unrelated to this PR but discovered while working on it.)

Fix some recordings missing the last keystroke

---

src/brogue/Recordings.c
src/brogue/RogueMain.c

Until now, Brogue wouldn't let you navigate to the last turn of a recording, either with arrow keys or entering the turn number, because the `gameOver()` / `victory()` functions could not display it while in fast-forward mode. Fixing the latter now allows seeking to the last turn without any issue.
For convenience, we now also allow entering a large turn number, e.g "99999" (easy to type!) and it is treated the same as seeking the end of the recording (i.e last turn).
Closes #309.

Allow seeking to the last turn of a recording

---

src/brogue/IO.c
src/brogue/Rogue.h
src/brogue/RogueMain.c

Equipping the initial equipment now writes messages to the archive, which are visible if the player looks after starting a game.
Clear these and any other possible message cruft by clearing the archive just before Hello and Welcome.
Issue #220

Clear the message archive before welcome()

---

changes/respiration-gas-trap-warning.md
src/brogue/Movement.c

Specifically, don't ask if the player is wearing identified respiration armor and steps on a caustic, paralysis or confusion trigger.  Stepping still shows the "--MORE--" prompt afterwards that must be dismissed.
Closes #149

Don't ask to step onto gas traps with respiration

---

src/brogue/Combat.c
src/brogue/Items.c
src/brogue/Rogue.h

Throwing (and enchanting, falling victim to acid mounds, or armor of burden..) implicitly equips an item as part of its implementation. These calls can now produce undesired messages.
Add a message flag as a boolean argument, to indicate if equip/unequip messages should be emitted.  Messages concerning cursed equipment are always produced.
Issue #220

Don't print equip messages when throwing

---

changes/falling-into-water.md
src/brogue/Architect.c
src/brogue/Items.c
src/brogue/Rogue.h
src/brogue/RogueMain.c
src/brogue/Time.c

Falling into deep water is now possible, without damage.
Damage is reduced when falling into other liquids (shallow water, bog) like in real life.
Closes #268

Allow falling into deep water

---

src/brogue/Grid.c
src/brogue/IO.c
src/brogue/MainMenu.c
src/brogue/Rogue.h

Formerly, `needsUpdate` was stored inside the `struct cellDisplayBuffer` to track which cells should actually be drawn to the screen with `plotChar` inside of `commitDraws`.
Now, `commitDraws` just remembers what it drew to the screen last (inside a new static global called `previouslyPlottedCells`). So the optimization is now applied fully automatically, with no support needed from the rest of IO.
This makes it much harder to accidentally forget to update a cell that's changed.
Also, in my brief tests where I did both at once and highlighted changes, I saw that there were even a few places where cells used to be updated redundantly which no longer occur!
The biggest benefit is that it's now obvious that `needsUpdate` is never used inside the various screen buffers passed around for …

Remove 'needsUpdate' from struct cellDisplayBuffer

---

changes/turns-since-last-staff-use.md
src/brogue/Items.c
src/brogue/Rogue.h

Players don't need to count turns if we simply record it for them.
Notice this is not quite the same thing as "turns until next charge", which is somewhat random.
Issue #280

Report turns since last use in staff description

---

src/brogue/Rogue.h
src/brogue/Time.c

In most games, tiles are normally exposed to fire up to 5 times per environment update. In rare circumstances (shooting a firebolt into a fire?) it can go up to 6 times. But it never goes higher than that... except when a bug causes an infinite loop involving `promoteTile()` and `exposeTileToFire()`, in which case the same tile can be exposed to fire over a thousand times, until Brogue runs out of stack space and crashes.
This commit limits `exposeTileToFire()` to 12 calls per tile per environment update. This fixes #341, without causing OOS errors on games unaffected by the bug. Tested on 10 victories and 10 ascensions from WebBrogue.

Fix infinite loop involving exposeTileToFire

---

changes/game-recording-considered-stable.md
src/brogue/IO.c
src/brogue/Recordings.c

We have now fixed all reload/playback errors that still existed in 1.9.3, namely:
- OOS due to secret door revealed by monster during auto-explore,
- OOS on the last turn of a recording missing the last keystroke.
Ignoring the possibility that 1.10 will introduce new sources of OOS errors that we are not yet aware of, now is a good time to declare the recording feature stable.

Take game recording feature out of beta

---

src/brogue/IO.c
src/brogue/RogueMain.c

The end game screens call
* `deleteMessages()`
* `message("I say good show")` and
* `funkyFade()`
..with the expectation that the final congratulatory message is only one visible in the message display (due to `deleteMessages()`) while the funky fade runs.
However, `message()` now redraws the entire message display area (for message collapsing) instead of simply inserting a new line at the bottom.  This makes the `deleteMessages()` calls ineffectual, and we see older message appearing again in the display.  Since they might have color code sequences, which funky fade does not understand, we see garbled output.
This change causes `funkyFade()` to ignore all displayed lines except the last one, enforcing the assumption it appears to be making.  It also drops the superfluous …

Funky fade now only keeps most recent message

---

Makefile
src/brogue/SeedCatalog.c

On Arch, the default `$CFLAGS` when building user-packages includes ` -Werror=format-security`, which causes builds to fail. 
There is only one line that needs a trivial fix, and I also added the compiler flag to the defaults.  
This seems like a pretty straight-forward, and non-controversial change, but I've only tested it on my setup so LMK if there are any issues you have =]

Compiler enforces string-format security

---

src/brogue/Items.c

Fix ally casting: The condition that checked whether the creature on a bolt's trajectory is on the same side as the bolt's caster didn't work when the caster is an ally of the player. In that case it gave a positive bonus for hitting the creature, instead of a negative one. The issue was that if the bolt was not cast by the player, then it was assumed to be cast by an enemy of the player.
Auto-kink unknown bolts: Until a wand or staff is identified, we need to hide whether it targets allies or enemies. We were achieving it by disabling the auto-kinking, but it would be more convenient for the user that we treat it like a throw and do our best effort to reach the target cell.
Fixes the issues reported by @zenzombie on `playtesting` Discord channel.

Auto-kinking improvements

---

src/brogue/Items.c

I fixed the issue by using `llabs()` instead of `abs()` following the suggestion given by the compiler but maybe you do not want to use C99 standard (`llabs` is available since C99 only).
The warning I got was:
```
src/brogue/Items.c:3353:23: warning: absolute value function 'abs' given an argument of type 'fixpt' (aka 'long long') but has parameter of type 'int' which may cause truncation of value
[-Wabsolute-value]
fixpt m = max(abs(step[0]), abs(step[1]));
^
src/brogue/Items.c:3353:23: note: use function 'llabs' instead
fixpt m = max(abs(step[0]), abs(step[1]));
^~~
llabs
```

Fix conversion from long long to int causing truncation.

---

src/brogue/Buttons.c
src/brogue/Dijkstra.c
src/brogue/Rogue.h

This is a small pass over the `Buttons.c` and `Dijkstra.c` files, to slightly improve code readability (and reduce code size) by moving variables closer to where they're used and remove genuinely unused code.
There are no functional changes in this PR.
---
`pdsInvalidate`, `pdsSetCosts`, and `pdsGetDistance` aren't used anywhere at all, so I removed them.
---
These three functions are only used inside `Dijkstra.c`, so I marked them as `static` and removed them from `Rogue.h`. This also removes `pdsLink` and `pdsMap` typedefs from `Rogue.h`:
```c
void pdsClear(pdsMap *map, short maxDistance, boolean eightWays);
void pdsSetDistance(pdsMap *map, short x, short y, short distance);
void pdsBatchOutput(pdsMap *map, short **distanceMap);
```
---
The `eightWays` fields is removed from `pdsMap`, …

Minor refactoring: declare variables closer to where they're used / remove unused code in Dijkstra + Buttons

---

src/brogue/Architect.c
src/brogue/Combat.c
src/brogue/Grid.c
src/brogue/IO.c
src/brogue/Items.c
src/brogue/Light.c
src/brogue/Monsters.c
src/brogue/Movement.c
src/brogue/Recordings.c
src/brogue/Rogue.h
src/brogue/RogueMain.c
src/brogue/SeedCatalog.c
src/brogue/Time.c
src/platform/curses-platform.c
src/platform/web-platform.c

This PR is designed to make the intent around "position"-affecting code just a little bit more clear, by introducing a type, `pos`, just for storing positions.
There are a lot of mechanical changes like `monst->xLoc` becoming `monst->loc.x`; though in a few cases we're able to replace
```c
monst->xLoc = blah.xLoc;
monst->yLoc = blah.yLoc;
```
with
```c
monst->loc = blah;
```
this doesn't replace _all_ instances of `x` and `y` on their own. I mostly focused on the cases that are used throughout the codebase (item `loc` and creature `loc`) and many of the instances where `short[2]` was used to represent a location instead of being fields on some larger type.
A second pass would find many/most of the places where `short x, short y` are being asked as parameters, and combine them into one. …

Refactoring: Great `pos`itioning - add a `pos` struct type, and use it in most places

---

changes/pathing-trusts-magic-map.md
src/brogue/Items.c

Currently, player pathing in deep dungeon levels prefers tiles which the player has stepped on or seen a monster step on, since these tiles cannot contain traps. This is not necessary if the level has been magic mapped, since the player knows the location of all traps. We can safely add the KNOWN_TO_BE_TRAP_FREE flag to all non-trap tiles when magic mapping, improving pathing through those levels.
Resolves #226

Add pathing updates to magic mapping

---

src/brogue/Items.c

When the armor rating is displayed in the info dialog, the previous
process of estimating the armor rating is something like this:
estimated = <armor_rating>                                    // => 50
estimated = estimated + (10 * strength_modifier / FP_FACTOR)  // => 50 - 25 = 25
estimated = estimated / 10                                    // => 25 / 10 = 2
But when it's equipped, the process ( IO.c:estimatedArmorValue ) is more
like:
estimated = <average_armor_rating> / 10                       // => 5
estimated = estimated + (strength_modifier / FP_FACTOR)       // => 5 + 2 = 3
Note, `10 * strength_modifier / FP_FACTOR` is 25 but
`strength_modifier / FP_FACTOR` is 2.
This commit modifies the process to estimate the value of unidentified,
unequipped armor to be exactly the same as the …

Fix rounding errors when estimating value of unidentified armor

---

changes/ctrl-key-in-terminal.md
src/platform/curses-platform.c
src/platform/term.c
src/platform/term.h

Fixes #383
I'm using GNOME Terminal for testing, so I can't guarantee this works on other terminals. Someone should probably test on other terminals before merging.

Fix control key commands not working in the terminal version

---

.gitignore

Saved screenshots aren't included in the gitignore, so git keeps thinking I want to commit them. No more.

Update gitignore to ignore screenshots

---

src/brogue/Items.c

```
src/brogue/Items.c: In function ‘identifyItemKind’:
src/brogue/Items.c:5713:26: warning: variable ‘lastItem’ set but not used [-Wunused-but-set-variable]
5713 |     short tableCount, i, lastItem;
|                          ^~~~~~~~
src/brogue/Items.c:5713:23: warning: unused variable ‘i’ [-Wunused-variable]
5713 |     short tableCount, i, lastItem;
|                       ^
```
Looks like it was introduced in f2bc84a

Fix two variable warnings

---

changes/+0-armor.md
src/brogue/Items.c

When +0 armor is identified as +0, prefix its name with the string "+0" to make it clearer that the armor is formally identified. (This non-gameplay change was previously based on the master branch rather than the release branch. This version is based on the release branch instead as desired.)

Label +0 armor as such

---

changes/discordant-monkey-ally.md
src/brogue/Monsters.c

Fix monster state when a discorded ally loses a stolen item in deep water

---

Makefile
src/brogue/Combat.c
src/brogue/Recordings.c

Generally by shortening input buffers.
Also replace a strcat with strncat.

Fix format-truncation warnings

---

changes/telepathy-vs-hallucination.md
src/brogue/IO.c
src/brogue/Monsters.c

Introduce a cute corner case: the player gets correct info about monsters during telepathy, even if also hallucinating.

Show correct monster during hallu if telepathic

---

src/brogue/IO.c

I'm not sure if this could cause any issues in practice, but with this change, Valgrind reports no errors when running the terminal version of Brogue (except when it crashes for an unrelated reason).

Fix an issue Valgrind identified in `getInputTextString`

---

changes/smart-id-hallucination.md
src/brogue/Items.c

A potion of hallucination is identified when thrown if all benevolent potions are either identified or magic detected

Auto-id hallucination when thrown, where possible

---

changes/stealth-range-display-shows-lit-and-dark.md
src/brogue/IO.c
src/brogue/Items.c
src/brogue/Monsters.c
src/brogue/Recordings.c
src/brogue/Rogue.h
src/brogue/RogueMain.c
src/brogue/Time.c
src/platform/main.c

* Internally rename "aggro range" to "stealth range"
* Clearer display of lit and dark areas now follows stealth range display mode, rather than true color display mode
* Tweak light and dark coloring
Closes #56

Show lit/dark highlights when stealth range is shown

---

src/brogue/Items.c

The auto-adjustment for lines considers whether the play knows about a tile, to avoid giving away secret information. However, it ignores the tile a little _too_ much, since it will happily use a path through an unknown cell even if a perfectly-good path no-risk path exists.
Here's an example of the new behavior in action. Standing in the same place, targeting the same cell, we get two different paths based on the available information, where when we don't know for sure what the cell is, the path avoids it (and then random tie-breaking happens to make it preferred in the second case).
I think the main question is whether the adjustment from a bonus from 5000 to 2500 is the "right" one. Maybe it should be less severe, like 4900 or 4000. Or, maybe it should depend on the number of unknown …

prefer throw/cast paths that don't use unknown cells

---

src/brogue/Architect.c
src/brogue/Combat.c
src/brogue/Items.c
src/brogue/Monsters.c
src/brogue/Movement.c
src/brogue/Rogue.h

#362 introduced the new `pos` type, describing a position in the dungeon, and added it to a lot of commonly-used types like `creature` and `item`. However, a lot of functions still asked for `short[2]` parameters.
This change addresses a big chunk of them - replacing `short[2]` with `pos` in a bunch more places. This ends up slightly reducing the line count.
Most of the changes is mechanically replacing e.g. `[0]` with `.x` and `[1]` with `.y`.
When `pos` are taken only as inputs, they're passed by value (e.g. `pos targetLoc`). When they're intended to be modified, they're passed by pointer, (e.g. `pos *returnLoc`). This is also more apparent at the use-site, since the caller has to explicitly write `updateLoc(&modifiedLoc, constLoc)` on the params that are updated.
One function, …

replace short[2] with pos in more functions

---

changes/wand-of-plenty.md
src/brogue/Items.c

This was one of the first ally nerfs we made. Now that other aspects of the build are more balanced, I think we should revert this, as the item is really weak currently.

Revert wand of plenty halving max HP

---

src/brogue/Math.c

The existing logic is "unfair", preferring some permutations over others. "Correct" shuffling should use something like the Fischer-Yates algorithm, which ensures that a uniformly random permutation is chosen.
This will break replays, since it changes how lists are shuffled.

use Fischer-Yates shuffle for fairer list shuffling

---

.github/workflows/build.yml

The version-less path doesn't seem to exist or have mt.exe in it in windows-2022

Use windows sdk 10.0.22000.0

---

changes/fix-poison-crash.md
src/brogue/Architect.c
src/brogue/Combat.c
src/brogue/Globals.c
src/brogue/IncludeGlobals.h
src/brogue/Monsters.c
src/brogue/Movement.c
src/brogue/Rogue.h
src/brogue/RogueMain.c
src/brogue/Time.c

This crash happened with seed 500500500; if you get the staff of poison from depth 7 and use it on the explosive goblin on depth 11 twice, the game crashes when the goblin dies. It can also happen with burning damage.
This fixes the crash by not removing monsters from `monsters` or `dormantMonsters` until `emptyGraveyard`, as well as modifying `iterateCreatures` to skip dying monsters. This approach should hopefully fix not only this crash, but also any similar crashes that haven't been seen yet.
Also fix an issue Valgrind identified in `getInputTextString`.
Fixes #404.
~~I've played a couple short games to look for issues, but I haven't played enough to be sure there aren't any issues. Also, I'm not sure whether this breaks save/replay compatibility or not; an early version did for some …

Fix crash when an explosive monster dies from poison or burning damage

---

changes/improve-absorption.md
src/brogue/Combat.c
src/brogue/Items.c

Increase absorption's minimum roll to 1.
This helps the runic to be less mediocre, and also to give it a stronger identity:
it now makes the player effectively immune to goblin conjurers,
and strong against jellies or packs of weak enemies.
Inspired by: #373

Unpopular item: improve Armor of Absorption

---

changes/denote-altar-items.md
src/brogue/Items.c

This can help players remember which of their items were checked out
from a library/vestibule type location.
The note is also added to door keys, but that doesn't seem to be a problem to me, as they were indeed found atop an altar.
The alternative would be to create a new member in struct theItem?
Closes #434

Add a note to items which were found atop an altar

---

changes/resurrection-prio.md
src/brogue/Monsters.c
src/brogue/RogueMain.c

The current behavior of resurrection altars (always resurrect most recently deceased ally) makes it a liability to have weak allies on your team. If a strong ally dies before a weak one, then altars will resurrect the weak one first. This change makes it so that allies who have been empowered more times—or, if that is tied, ones with a greater monsterID—will be resurrected first instead. This removes the liability inherent in weak allies and allows ally players to control which allies they get back by rationing their empowerment.

Ally resurrection favors more powerful allies

---

src/brogue/Architect.c
src/brogue/Rogue.h

These could alternatively be scaled to the `AMULET_LEVEL` but precise control is useful in shorter games. e.g. in RB if you just divide by 4, the first level would have lava, whereas it should have water for thematic reasons.

Create defines for minimum levels for lava and brimstone liquids

---

changes/improve-quit-commands.md
src/brogue/IO.c

"Quit without saving" is now "Quit and abandon game"; "Suspend game and quit" is now "Save and exit". These commands are now next to each other in the menu. Also remove the commands for opening saved games and recordings from within a game, as they could be used for save scumming and don't seem to have much purpose otherwise; both of those actions can now only be done from the main menu or from a recording.
Fixes #458.

Improve the wording of commands to exit the game, and remove commands that can be used for save scumming

---

src/brogue/IO.c
src/brogue/Items.c
src/brogue/Rogue.h

For instance, when equipping an unenchanted chain mail at 12 strength, this makes sure the displayed armor rating is always '2' instead of '3', whether it's identified or not. This also merges a few duplicate calculations together so they're less likely to be inconsistent in the future (though there's still some duplication).
Fixes #385.

Fix rounding when predicting armor ratings

---

src/brogue/Items.c

Most bolts use `magnitude` for the sizeof the effect. This allows the size of the effect to be controlled in Globals.c. `magnitude` is also used for some graphical niceties which change with the scale but basically look fine with various magnitudes in my testing.

Use bolt magnitude for duration of invisibility bolt effect

---

src/brogue/Rogue.h
src/brogue/RogueMain.c

I find this super handy. Nice I guess to be able to turn it on and off but this implementation follows the current style.

Add omniscence mode for wizard, defaulted to off

---

.gitignore
Makefile
recipes/brogue.mk
recipes/brogue_windows.mk
recipes/o.mk
recipes/releases.mk

This is a bit experimental, but it should mean you don't have to remember to do `make clean` when changing build options. In fact, `make clean` has been removed; use `make -B <target>` if you need to force a rebuild.

Ensure builds depend on variables and recipes

---

changes/issue-499.md
src/brogue/IO.c
src/brogue/Items.c
src/brogue/Rogue.h
src/brogue/Time.c

Suggested in #499 - this is an implementation of the "debuf" variant.  Equipping cursed items adds time to the "Cursed" debuf.  Cursed items cannot be removed until the curse ends.
Not sure if 1000 turns is the right number for duration though.

Cursed items add long-duration debuf, then uncurse

---

changes/issue-514.md
src/brogue/Items.c
src/brogue/Time.c

Probably needs play testing/balancing to get the right "feel".
Bloodwort now speeds recovery from negative effects (suggested in #514):
- Hallucination
- Confusion
- Nausea
- Slowed
- Weakened
- Poisoned
- Darkness

Bloodwort speeds recovery of negative effects (poison, weakness, etc)

---

src/brogue/Items.c

After some more testing, I noticed the curse status did not clear when enchanting.  This fix cleans up the steps for uncursing  items and centralizes the logic.

Fix for uncursing items using different means

---

src/platform/tiles.c

A missing check for y0 >= 1 makes it possible to underflow scaledY if y1 >= 2 and y0 == 0. Detected by compiling with clang using -fsanitize=address.

Fix possible stack underflow in downscaleTile

---

src/brogue/Recordings.c

Noticed while building on OpenBSD.  Seed is uint64_t, so `%llu` plus a cast to unsigned long long is better and I believe more portable than assuming it's a long (or use the PRIu64 macro from inttypes.h, but personally I prefer the cast to long long), and while here change the other `%li` to `%lu` since the other variables are `unsigned long`.

fix a fprintf format string

---

src/brogue/Architect.c
src/brogue/Buttons.c
src/brogue/IO.c
src/brogue/Items.c
src/brogue/MainMenu.c
src/brogue/Monsters.c
src/brogue/Rogue.h
src/brogue/RogueMain.c
src/brogue/Time.c

Some previous PRs added the `pos` type, for locations in the dungeon. This PR adds the `windowpos` type, for positions in the window.
The main reason for this is to prevent confusion (or ambiguity) between "dungeon" coordinates and "window" coordinates. It bakes the distinction into function signatures and allows for more helpful helper functions.
For example, the new `mapToWindow` function converts from `pos` to `window`, so you can write `mapToWindow(p)` instead of `mapToWindowX(p.x), mapToWindowY(p.y)` -- though the old macros are still around, as this doesn't apply to all uses.
This PR updates `plotCharWithColor` and `plotCharToBuffer` to ask for a `windowpos` instead of an `x` and `y` -- right now, these are the only functions which actually use the new `windowpos`.

Create generic `windowpos` type for window coordinates

---

src/brogue/Rogue.h

A C89 (and through later standards up to C23) function declaration with empty arguments `()` actually means "any arguments" and not "no arguments". So the compiler doesn't complain about this as loudly as it should. The "right" spelling to specify that no arguments are taken is `(void)`.
This is the only function in the codebase which has this problem. It's an easy mistake to make (and to fix).
There aren't any immediate problems, so this isn't fixing any real issues. You just lose some static type-checking ability if the function were called from another file.

fix declaration of 'armorValueIfUnenchanted' to include args

---

src/brogue/Architect.c
src/brogue/Combat.c
src/brogue/IO.c
src/brogue/IncludeGlobals.h
src/brogue/Items.c
src/brogue/Light.c
src/brogue/Monsters.c
src/brogue/Movement.c
src/brogue/Rogue.h
src/brogue/RogueMain.c
src/brogue/SeedCatalog.c
src/brogue/Time.c
src/brogue/Wizard.c

In previous PRs, the `pos` type helps organize coordinate info, but the most common operation that's done with coordinates are looking them up in the global `pmap`. And manually writing out
```c
pmap[loc.x][loc.y].flag |= ...
```
is tedious and error-prone if `loc` is anything more than a short variable name, since you need to repeat it twice with `.x` and then `.y`. This PR adds a new global helper function `pmapAt` that returns a pointer, allowing the above to be written as
```c
pmapAt(loc)->flag |=
```
it returns a pointer because it's a "real" function instead of a macro - this adds a little bit of extra friction, but saves all the headache of dealing with a new macro.
This function is declared as `static inline`  in the header - the compiler will therefore not complain about multiple …

create pmapAt and tmapAt helper functions

---

src/brogue/Architect.c
src/brogue/Combat.c
src/brogue/IO.c
src/brogue/Items.c
src/brogue/Monsters.c
src/brogue/Movement.c
src/brogue/Rogue.h
src/brogue/RogueMain.c

This PR is a minor refactoring that improves some type-safety by allowing more use of `pos` instead of individual coordinates. It only adds net 3 lines of code but deletes a lot of repeated variable references.
- a new `INVALID_POS` constant is just `(pos){.x = -1, .y = -1}`, which gets used throughout the codebase
- `isPosInMap` is a new predicate, behaving like `coordinatesAreInMap` but for the `pos` type
- `splitMonster` now accepts a `pos` instead of `short x, short y`
- `distanceBetween` now accepts two `pos` args instead of 4 shorts
- Almost every single call to `distanceBetween` already had at least one `pos` argument, and most of them had 2

Use `pos` type for `distanceBetween` & `splitMonster`

---

src/brogue/Combat.c
src/brogue/IO.c
src/brogue/Monsters.c
src/brogue/Rogue.h
src/brogue/Time.c

There were a few leftover creature variables `lastSeenPlayerAt` and `targetCorpseLoc` which were tracked as `short[2]` instead of `pos`. This PR switches them over, and fixes up the functions that use them to use `pos` as well.
---
One pattern that's not addressed in this PR that I think would be fruitful to tackle in the future is this:
```c
pos targetLoc = {
monst->loc.x + nbDirs[dir][0],
monst->loc.y + nbDirs[dir][1]
};
```
a helper function `pos stepNeighbor(pos, short)` that handles this coordinate logic would be convenient.

Use pos type for creature variables

---

make/brogue.mk

Couldn't find a reasonable workaround for this issue.

When debugging on Windows don't embed manifest

---

src/brogue/Architect.c
src/brogue/Combat.c
src/brogue/Dijkstra.c
src/brogue/IncludeGlobals.h
src/brogue/Monsters.c
src/brogue/Movement.c
src/brogue/Rogue.h
src/brogue/RogueMain.c
src/brogue/Time.c

One of the most common operations on `pos` is moving one step in the provided direction; this PR adds the `pos posNeighborInDirection(pos, enum direction);` function which does this for you.
Because many of the (new) uses of this function also call `monsterAvoids`, and it was already being passed a (deconstructed) `pos` in quite a few places, I also converted `monsterAvoids` from `boolean monsterAvoids(creature*, short, short)` into `boolean monsterAvoids(creature*, pos);`.

add `posNeighborInDirection` utility function + update monsterAvoids to accept `pos`

---

src/brogue/Architect.c
src/brogue/IO.c
src/brogue/Items.c
src/brogue/Monsters.c
src/brogue/Movement.c
src/brogue/Rogue.h

This PR replaces all of the remaining uses of `short[2]` to describe a position with the `pos` type. This improves clarity and type-safety. Combined with some cleanup in the affected functions, net 39 lines get deleted.
(There are still lots of functions that take `(short, short)` when they ought to take `pos` or `windowpos` instead, but that's for the future)

Replace `short[2]` with `pos`

---

src/brogue/Architect.c
src/brogue/Combat.c
src/brogue/Dijkstra.c
src/brogue/IO.c
src/brogue/Items.c
src/brogue/Monsters.c
src/brogue/Movement.c
src/brogue/Rogue.h
src/brogue/Time.c
src/brogue/Wizard.c

The `monsterAtLoc` and `dormantMonsterAtLoc` functions are commonly-used, but they still didn't take a `pos` argument. This change should have no observable difference in behavior.

monsterAtLoc takes a 'pos' instead of two shorts

---

src/brogue/Architect.c

This is a really small refactor to `buildAMachine`, which is one of the most complicated functions in `Architect.c`, spanning about 850 lines. To make it a little bit easier to understand, I've reduced the scope of most of the "looping" variables, which makes it clearer that there's no long-range dependencies between their values.

refactor `buildAMachine`

---

src/brogue/Architect.c
src/brogue/Items.c
src/brogue/Monsters.c
src/brogue/Rogue.h

This is a small refactor to the `randomMatchingLocation` so that it writes to a `*pos` argument, instead of two `short*` arguments.

convert randomMatchingLocation to take a 'pos' argument

---

src/brogue/Architect.c
src/brogue/Combat.c
src/brogue/Dijkstra.c
src/brogue/Grid.c
src/brogue/Items.c
src/brogue/Monsters.c
src/brogue/Movement.c
src/brogue/Rogue.h
src/brogue/RogueMain.c
src/brogue/Time.c

This PR updates functions defined in `Monsters.c` so that they take `pos` arguments instead of `short x`, `short y`. It does some light refactoring inside those functions to make better use of the new `pos` argument when possible.

Refactor monsters.c functions to take `pos` argument

---

changes/issue-602.md
src/brogue/Items.c

Fixes issue #602.
- Unidentified rings can no longer have higher bonuses than they will have once identified
- Unidentified positive rings give `1 + timesEnchanted` prior to identification, not  `1 + timesEnchanted - 1` 
Test evidence:
```
Unidentified +1 ring of regen, 2 enchants
1774        if (theItem->category != RING) {
(gdb) n
1777        if (!(theItem->flags & ITEM_IDENTIFIED)
(gdb)
1782            return min(theItem->enchant1, theItem->timesEnchanted + 1);
(gdb) print theItem->enchant1
$1 = 3
(gdb) print theItem->timesEnchanted
$2 = 2
(gdb) n
updateRingBonuses () at src/brogue/Items.c:7776
7776                        break;
(gdb) print rogue.regenerationBonus
$3 = 3
Unidentified +3 ring of regen, 3 enchants
1774        if (theItem->category != RING) {
(gdb) n
1777        if …
```

Fix bonuses for enchanted, unidentified rings

---

Makefile
src/brogue/Architect.c
src/brogue/Combat.c
src/brogue/Grid.c
src/brogue/IO.c
src/brogue/Items.c
src/brogue/Light.c
src/brogue/MainMenu.c
src/brogue/Math.c
src/brogue/Monsters.c
src/brogue/Movement.c
src/brogue/Recordings.c
src/brogue/Rogue.h
src/brogue/RogueMain.c
src/brogue/Time.c
src/brogue/Wizard.c
src/platform/platform.h
src/platform/platformdependent.c
src/platform/tiles.h
src/variants/GlobalsBrogue.c
src/variants/GlobalsBrogue.h
src/variants/GlobalsRapidBrogue.c
src/variants/GlobalsRapidBrogue.h

This PR does several things:
* Adds `-Wmissing-prototypes` to warn about functions that don't have a prototype
* Adds `(void)` to prototypes of functions that take no arguments (otherwise the warning doesn't work properly)
* I ran a script to add "static" to functions that should have it, based on the compiler output (the script isn't included in this PR since I don't think it's useful after this, but I can add it if requested)
* Removes most static functions that the compiler now warns are unused (I kept some that seem to be for debugging)
This doesn't have any gameplay changes.

Add static to all functions that should have it, and remove several unused static functions

---

src/brogue/Architect.c
src/brogue/Combat.c
src/brogue/IO.c
src/brogue/Items.c
src/brogue/Monsters.c
src/brogue/Movement.c
src/brogue/Rogue.h
src/brogue/RogueMain.c
src/brogue/Time.c
src/brogue/Wizard.c

About half of calls to `refreshDungeonCell` were already `pos` values being split apart, so this generally cleans things up a lot.

refreshDungeonCell refactored to take 'pos' argument

---

src/brogue/Items.c

Closes #611
Makes it so that the potion of detect magic does not consider itself when listing whether any magic was detected.

Potions of detect magic should not detect themselves

---

changes/names-for-blueprints.md
src/brogue/Architect.c
src/brogue/Rogue.h
src/variants/GlobalsBrogue.c
src/variants/GlobalsRapidBrogue.c

Names that were previously comments have been included as a `name` string for each blueprint. This was done using a regexp.
Messaging during blueprint creation has been updated to use these names.
Only affects debug messaging (under D_MESSAGE_MACHINE_GENERATION), no in-game effect

Added names to blueprints

---

src/brogue/Architect.c
src/brogue/Globals.c
src/brogue/Rogue.h

This should be a no-behavior change. Here are a few of the macros defined in Brogue.h converted into regular functions.
Some of them are `inline static`s declared in the same spot as the old macro; others need to be moved into `.c` files because they rely on globals being in scope.

convert several helper macros into ordinary functions

---

changes/floor-ordinals.md
src/brogue/RogueMain.c

The welcome message previously assumed the Amulet of Yendor was on a -th floor. But, for example, in bullet brogue, it's on the 3-rd floor. This change supports all floor numbers.

Adding the correct floor ordinal in the welcome message

---

src/brogue/Rogue.h
src/brogue/SeedCatalog.c
src/platform/main.c

Previously --print-seed-catalog could exceed the max depth of shorter variants. `printSeedCatalog` now returns an `errorCode` and writes to an `errorMessage`.

Adding guarding on --print-seed-catalog so it won't exceed the deepestLevel

---

src/brogue/Architect.c
src/brogue/Combat.c
src/brogue/Dijkstra.c
src/brogue/Globals.c
src/brogue/Grid.c
src/brogue/IO.c
src/brogue/Items.c
src/brogue/Monsters.c
src/brogue/Movement.c
src/brogue/Rogue.h
src/brogue/RogueMain.c
src/brogue/Time.c
src/brogue/Wizard.c

Almost all of the individual call-sites were refactored with a smart find+replace regex, so there shouldn't be any accidental typos.
Three functions have been refactored to take `pos` arguments instead of `short, short` coordinates:
- `terrainFlags`
- `terrainMechFlags`
- `cellHasTerrainFlag`

use 'pos' type to look up terrain flag values

---

src/brogue/Buttons.c
src/brogue/GlobalsBase.c
src/brogue/GlobalsBase.h
src/brogue/Grid.c
src/brogue/IO.c
src/brogue/Items.c
src/brogue/MainMenu.c
src/brogue/Movement.c
src/brogue/Recordings.c
src/brogue/Rogue.h
src/brogue/RogueMain.c
src/brogue/Wizard.c

Before this change, most of the time, a `cellDisplayBuffer buf[COLS][ROWS]` was created wherever needed. Now, you can spell this as `screenDisplayBuffer buf;`
There are a few ways that this is nicer:
- The new type remembers the correct size for the buffer, so it doesn't have to be written down `[COLS][ROWS]` every time
- The new type is a _struct_ instead of an _array_, so it has more-consistent semantics: no pointer decay; taking references is explicit instead of implicit, etc.
This PR just swaps out all of the existing `cellDisplayBuffer` arrays to references to this new type. There's no other changes.
---
Eventually, I'd like to refactor a bit more, so that the screen is more "encapsulated" - references to `.cells` should be restricted to a handful of functions, so that the screen …

create `struct screenDisplayBuffer` type (`cellDisplayBuffer[COLS][ROWS] ---> screenDisplayBuffer`)

---

src/brogue/GlobalsBase.c
src/brogue/Recordings.c
src/brogue/Rogue.h

This is a pretty hands-off fix for the issue where the recording buffer is never flushed when using `--print-seed-catalog`.
The real fix is to ensure that `flushBufferToFile` will always flush the buffer, regardless of if a recording file is present.
Guarding is also added to `recordChar` to avoid buffer overflows.
This change avoids creating a new game state of `isPrintingSeedCatalog`.
An addition we could do is to avoid writing to the recording buffer if there is no recording file.

Ensuring recording buffer is always flushed even with no recording file

---

src/brogue/Architect.c
src/brogue/Rogue.h
src/brogue/RogueMain.c

Rapid Brogue seed 519 cannot place stairs in level 2 since there are no qualifying squares (basically every square is part of a machine). This patch rerolls the level when this (very rare) case occurs.

Redo the level if stairs cannot be placed

---

src/brogue/IO.c

Previously `getInputTextString` in debug builds would overwrite the edge of the `displayBuffer` due to the use of `plotCharWithColor`. This happened, for example, when printing the default save file name for debug builds (which have long version strings).
This change adds guarding to the `plotCharWithColor` and `plotCharToBuffer` (which was already there but only as an assert for debug builds). I haven't changed `plotChar` since it's a lower level function where the caller will have to take responsibility for not writing outside of bounds.

Adding out-of-range guard to plotChar+ functions

---

src/brogue/Buttons.c
src/brogue/IO.c
src/brogue/Items.c
src/brogue/Light.c
src/brogue/MainMenu.c
src/brogue/Movement.c
src/brogue/Recordings.c
src/brogue/Rogue.h
src/brogue/RogueMain.c
src/brogue/Time.c
src/platform/null-platform.c
src/platform/platform.h
src/platform/platformdependent.c
src/platform/sdl2-platform.c

This is a refactor of the way that buttons are drawn and some button-related events are handled. The main idea is to remove `dbuf` and `rbuf` from the `buttonState` struct, and instead just re-render the buttons whenever they need to be added to the screen.
This gets rid of a lot of low-level logic for highlighting/unhighlighting buttons, and makes the behavior of saving/restoring the screen clearer, because it becomes more local, i.e. now you'll see this logic explicitly:
```C
// All in one block of code:
screenDisplayBuffer rbuf;
overlayDisplayBuffer(..., &rbuf); // save the original screen
// draw stuff & wait for input 
...
// Restore the screen to how it was before this block executed:
overlayDisplayBuffer(&rbuf, NULL);
```
effectively this is what was happening before, but figuring …

Simplify button-drawing logic

---

src/brogue/Buttons.c
src/brogue/IO.c
src/brogue/Items.c
src/brogue/MainMenu.c
src/brogue/Movement.c
src/brogue/Recordings.c
src/brogue/Rogue.h
src/brogue/RogueMain.c
src/brogue/Wizard.c

This PR is only refactoring; it should not cause any visible changes.
---
A common pattern in the Brogue codebase is to do the following:
```c
screenDisplayBuffer dbuf;
screenDisplayBuffer rbuf;
clearDisplayBuffer(&dbuf);
fillBufferWithSomeKindOfGraphics(&dbuf); // some arbitrary logic
overlayDisplayBuffer(&dbuf, &rbuf);
// ... wait for events or something ...
overlayDisplayBuffer(&rbuf, NULL); // put the screen back
```
The second argument to `overlayDisplayBuffer` is used to store the old screen, so that drawn graphics can be reverted later. This is convenient, but it makes `dbuf` and `rbuf` usage look very similar, since they're both just `screenDisplayBuffer`s.
We can make the distinction clearer by introducing new functions:
```c
// A `SavedDisplayBuffer` holds a previous version of …
```

Refactor screen save&restore logic

---

.github/workflows/test-seed-catalog.yml
test/compare_seed_catalog.py
test/seed_catalogs/seed_catalog_brogue.txt
test/seed_catalogs/seed_catalog_rapid_brogue.txt
test/update_seed_catalogs.py

This adds a new github action to check the output of seed catalog for each variant and fails if it has changed.
This will detect any unintentional changes to dungeon generation.
If any changes have expected dungeon generation changes, the commits also need to update `test/seed_catalogs`.
This test could apply to `master` but requires the seed catalog crash fix which is only currently in `release`.

Adding github action to monitor for dungeon gen changes

---

changes/jellies-must-die.md
src/brogue/Combat.c

Fixes #91 
Jellies will now die without splitting when hit with a jelly slaying weapon or a weapon of quietus that procs.

Quietus and jelly slaying weapons kill jellies before they split

---

changes/allow-ally-spear-attacks-over-player.md
src/brogue/Monsters.c

Fixes #119 
Downstream logic in `moveMonster` prevents allies from attacking each other, so `willingToAttackPlayer` can be true.

Allow allies to spear attack over the player

---

src/brogue/Architect.c
src/brogue/Dijkstra.c
src/brogue/Grid.c
src/brogue/IO.c
src/brogue/Items.c
src/brogue/Monsters.c
src/brogue/Movement.c
src/brogue/Rogue.h
src/brogue/SeedCatalog.c
src/brogue/Time.c

Updates these three functions to take `pos` arguments instead of two `short` arguments:
- `cellHasTMFlag`
- `cellhasTerrainType`
- `getCellAppearance`

Refactor to take `pos` arguments

---

changes/prevent-spear-attacks-around-corners.md
src/brogue/Movement.c

Fixes #103 
I find the move/attack logic to be mind-bendingly complex and I won't say how long I spent on this one. Anyway, it turns out that spear/whip attacks were being treated differently for discordant monsters vs. hunting monsters vs. allies.
This fix adds a check on the neighboring tile in the direction of attack. The attacker must generally be able move to the tile. In the screenshot below, the player can attack the goblin but goblin cannot attack the player. Before the fix, if the goblin was discordant it would happily attack the player. Also, if the player was instead an enemy monster and the goblin was an ally, previously the goblin would happily attack.

Prevent spear and whip attacks around corners

---

changes/strength-potion-not-immediate.md
src/brogue/Items.c

This fixes bug [#366](https://github.com/tmewett/BrogueCE/issues/366).
This removes the player's weakened status as soon as the potion is drunk.  It's done again at the end of the turn as well, but I don't see how that would cause a problem.  
It's possible that the better way to do this is to make another generic function like applyInstantTileEffectsToCreature (but for potions), but I don't know of any other potions that need an effect like this to happen immediately.  If there are, it might make sense to put them into something like applyInstantPotionEffectsToPlayer (which I'd be happy to try to tackle if that's the correct thing to do in this case).
(This is my first bug fix in C, my first attempt at using github.)

Fixed strength potion not curing weakness immediately

---

changes/attack-discordant-allies.md
src/brogue/Monsters.c
src/brogue/Movement.c

Fixes #213 
Fixes #644 
This PR makes no changes to the "unAlly" rules. A discordant ally will remain an ally even if attacked.
Discordant allies will not swap places. The player can attack the ally but the player will be prompted for confirmation as long as the player is neither confused nor hallucinating (and not telepathic).

Player can attack discordant ally, not swap places

---

src/brogue/IO.c
src/brogue/Recordings.c
src/brogue/Rogue.h
src/brogue/RogueMain.c

Previously, file save operations used the message pane, which is a dungeon UI component. However, when the player wins or dies, the dungeon UI is no longer visible, so the location of the message pane and any related message management is no longer relevant. 
This change updates the UI so that game save and recording save operations use a centered dialog. The dialog title displays the prompt and the filename is entered on the line below, which accommodates much long file names. This is especially nice for the long filenames generated by debug builds but is also generally useful since the filename now includes a variant identifier and version number and can also include the mode name (e.g. wizard). I added some long filename handling so the initially generated filename is truncated to fit …

Use a dialog window when saving a game or recording

---

src/brogue/Monsters.c

No code changes, just some documentation.

Document monster movement and visibility functions

---

changes/item-under-player.md
src/brogue/IO.c
src/brogue/Items.c
src/brogue/Movement.c
src/brogue/Rogue.h
src/brogue/RogueMain.c

Fixes #214 
The only breaking change is the removal of HAS_ITEM in the player placement logic of startLevel in RogueMain. The other changes passed regression testing against the release branch.

Handle items under the player on level arrival and generally

---

changes/auto-targeting.md
src/brogue/IO.c
src/brogue/Items.c
src/brogue/Monsters.c
src/brogue/Rogue.h
src/brogue/Wizard.c

Replaces PR #658 
Fixes #420 
Centralizes the player auto-targeting logic and makes many behavior modifications, as described in the changes file. I tried to implement improvements that I think make sense, but let me know if I should back out any of them.
These changes should have no effect on replays because I think only the final selected target is recorded, not the candidate targets and I don't think the method of target selection (auto vs. manual) is relevant.

Improve and refactor auto-targeting when throwing something or using a staff or wand

---

src/brogue/Monsters.c
src/brogue/Rogue.h
src/brogue/Wizard.c

Monster HP, attack speed, and movement speed weren't getting set correctly for some mutations.

Fix mutated monster creation in wizard mode

---

changes/release-the-kraken.md
src/brogue/Combat.c

Fixes #521
The initial constraint based on the location of the deceased is now less restrictive and the distance map is calculated based on the monster type of the ally.

Krakens can learn from monsters that die in deep water

---

changes/discordant-pixie
src/brogue/Monsters.c

Fixes #438 
Negation for the sole purpose of removing discord is a positive effect and is a bug.

Fix discordant allies negating other discordant allies

---

changes/kraken-obsidian.md
src/brogue/Architect.c
src/brogue/Globals.c
src/brogue/Rogue.h

Fixes #372 
The problem was the liquid layer retains SHALLOW_WATER when a tile is turned to obsidian by dragonfire.

Fix obsidian treated as water

---

changes/monster-details.md
src/brogue/Globals.c
src/brogue/Globals.h
src/brogue/GlobalsBase.h
src/brogue/IO.c
src/brogue/Items.c
src/brogue/Monsters.c
src/brogue/Rogue.h

Related to #664.
If the monster has both negatable and non-negatable traits and the player has the means to negate the monster, the non-negatable traits are listed first. The negatable traits are shown next, along with the list of item kinds that can negate the monster.
If the monster is destroyed by negation, shattering, or tunneling and the player has a known item of that type, that fact is displayed in the details screen.

Add negation, shattering and tunneling effects, if any, to monster details

---

changes/siezed-while-submerged.md
src/brogue/Combat.c

Fixes #578 
If the player is seized by a submerged monster they can see (i.e. player is also submerged), it will now immediately surface so it can be targeted with staffs/wands.

When submerged player is seized, monster immediately surfaces

---

changes/game-stats.md
src/brogue/MainMenu.c
src/brogue/Rogue.h
src/brogue/RogueMain.c
src/platform/platformdependent.c

Saves run history to a file and adds a new menu option for viewing game statistics.
The player can reset their "Recent" stats at any time.

Save run history and add game stats screen

---

src/brogue/Items.c

Fix a bug where some known good staffs of unknown kind (like blinking and tunneling) would not autotarget enemies, leaking information about the staff kind.

Fix regression autotarget tunnel & blink staff bug

---

src/brogue/Combat.c
src/brogue/Items.c
src/brogue/Rogue.h

Fixes #699. Removed monster splitting from moralAttack(). Confirmed expected behavior with thrown weapons, damage staffs, standard weapons, quietus runic, and paralysis runic.

Bugfix paralysis runic

---

src/brogue/Combat.c
src/brogue/Monsters.c
src/brogue/Movement.c
src/brogue/Rogue.h

I have replaced every `creature **hitList` with `const creature **hitList`. This removes the incompatible const pointer errors with GCC 14 and allows for compilation without the `-Wno-error=incompatible-pointer-types` flag. However it introduces many strncpy and strncat warnings so I am not sure if this is an appropriate solution.
Refs #696 
Any advice would be appreciated.

Replaced hitList with const hitList

---

src/brogue/Items.c

Fixes issue introduced by #669 where dormant turrets would not get destroyed by shattering and instead would become active.
Confirmed on these seeds:
Seed 366139372 D19 has dormant turrets activated by a key.
Seed 366153074 D15 has a sentinel in the outer wall.

Fix regression bug with shattering and dormant turrets

---

src/platform/curses-platform.c

This fixes the following compiler error.
src/platform/curses-platform.c:226:5: error: incompatible function pointer types initializing
'char ()(short, PauseBehavior)' (aka 'char ()(short, struct PauseBehavior)')
with an expression of type 'char (short)' [-Wincompatible-function-pointer-types]
curses_pauseForMilliseconds,
^~~~~~~~~~~~~~~~~~~~~~~~~~~

Fix clang error with incompatible function pointer types

---

src/brogue/Rogue.h
src/brogue/SeedCatalog.c
src/variants/GlobalsBrogue.c
src/variants/GlobalsRapidBrogue.c

Fixed seed catalog altars for variants

---

src/brogue/Movement.c

Fix: #711 
The problem stemmed from the concatenation process in the [describeLocation](https://github.com/tmewett/BrogueCE/blob/cf12bf893eb963771d628dfc78b5a62bf71ddda8/src/brogue/Movement.c#L349) [Movement.c] function. Specifically, when appending strings, the code did not consistently check if a space already existed at the end of one string before adding another space. This could result in double spaces when the next string was concatenated.
To resolve this, I added a check to ensure that a space is only added if one does not already exist at the end of the string. The updated code snippet ensures that the verb string always ends with exactly one space before concatenating the next part of the sentence:
```c
if (verb[strlen(verb) - 1] != ' ') {
strcat(verb, " ");
}
```

Fix formatting issue in describeLocation function

---

linux/io.github.tmewett.brogue.metainfo.xml

https://www.freedesktop.org/wiki/Distributions/AppStream/
Needed for this application to show up in various Linux software centers such as gnome-software and discover.

Add appstream metadata

---

src/brogue/Recordings.c
src/brogue/Rogue.h

Fixes some small warnings caught by clang about arrays being sized incorrectly:
- `keyList` was slightly too short to have space for the last item, `UNKNOWN_KEY`
- `parentSpawnedItems` were recently increased to length `MACHINES_BUFFER_LENGTH` (actually 200) in the `.c` file, but the declaration in the `Rogue.h` header was missed

fix clang warnings - adjust array sizes

---

src/brogue/IO.c
src/brogue/Rogue.h
src/brogue/RogueMain.c
src/platform/main.c

Adds a `--hide-seed` command line option that hides the seed display when playing. This is used in web-brogue where seeds are obscured to players until the end of game to avoid players trivially practising the same seed offline.

Add seed hiding controlled by cmd line option

---

src/brogue/Architect.c
src/brogue/Combat.c
src/brogue/Grid.c
src/brogue/Items.c
src/brogue/Monsters.c
src/brogue/Movement.c
src/brogue/Rogue.h
src/brogue/RogueMain.c
src/brogue/Time.c

Replaces the 4 coordinate parameters (2 out, 2 in) with a single input `pos` and a return `pos` value.
The function previously returned a `boolean`, but this value was never checked by any of its callers. The `false` return state is now represented by returning `INVALID_POS`.
There should be no behavioral changes in this PR.

use pos type for `getQualifyingPathLocNear`
