tmewett/BrogueCE

CHANGELOG.md
src/brogue/RogueMain.c

rememberedItemQuantity and rememberedTMFlags were not saved and restored correctly

Remember levels and items correctly when changing levels

---

CHANGELOG.md
Makefile
config.mk
src/brogue/IO.c
src/brogue/MainMenu.c
src/brogue/Recordings.c
src/brogue/Rogue.h
src/brogue/RogueMain.c
src/platform/curses-platform.c
src/platform/main.c
src/platform/platform.h
src/platform/platformdependent.c
src/platform/sdl2-platform.c
src/platform/web-platform.c

Add WebBrogue platform

---

src/brogue/IncludeGlobals.h

This was needed to compile with emscripten

Add missing externs on two global variables

---

Makefile
src/brogue/Rogue.h
src/brogue/RogueMain.c
src/platform/main.c

Now free of merge commits and unrelated code!

Turn wizard mode into a command line option flag

---

linux/make-link-for-desktop.sh

Desktop entry now matches Games category in menu.
Add entry description on Russian and German languages.
_It continues #93._

Update desktop entry

---

changes/csv-seed-catalog.md
changes/dungeon-version.md
src/brogue/Globals.c
src/brogue/IncludeGlobals.h
src/brogue/Items.c
src/brogue/Rogue.h
src/brogue/SeedCatalog.c
src/platform/main.c

The updated command line arguments are below.
--print-seed-catalog [START NUM LEVELS] [--csv]

Add seed catalog csv output

---

changes/fix-incorrect-runic-names.md
src/brogue/Items.c

fix incorrect runic name for dampening armor and slowing weapons

fix incorrect runic name for dampening armor and slowing weapons

---

src/brogue/Movement.c

Some code was duplicated which didn't need to be.
Non-functional patch.

Simplify randValidDirectionFrom logic

---

src/brogue/Rogue.h
src/brogue/Utilities.c
src/platform/main.c

Create Utilities.c and move 'endswith' and 'append' from main.c

Create Utilities.c 

---

.gitignore
src/brogue/Recordings.c
src/platform/curses-platform.c
src/platform/sdl2-platform.c
src/platform/term.h
src/platform/web-platform.c

A series of minor tweaks and fixes

---

src/brogue/Recordings.c

Also move newlines to end of string

Add player turn number to OOS stdout panic message

---

.github/workflows/build.yml

apt update on linux build

---

.github/workflows/build.yml
Makefile

Fix a quoting issue introduced by the use of `;` as well.

Add mt manifest tool to PATH

---

.github/workflows/build.yml
.gitignore
Makefile

Iteration on #198. CC @withinwheels

Add release rules to Makefile and make them in GH Actions

---

changes/fix-stuck-status-blink-teleport.md
src/brogue/Items.c
src/brogue/Monsters.c
src/brogue/Rogue.h

Fix stuck status on blink or teleport

---

src/brogue/Globals.c

To fix this issue: #[285](https://github.com/tmewett/BrogueCE/issues/285)

Make wand of empowerment spawn chance higher as in v1.7.4

---

CONTRIBUTING.md

Closes #304
Closes #308 
You asked for this to be rebased to release, you got it! Should release be the default branch?

Explain where to report web-brogue issues

---

changes/dont-yeet-your-melee-weapon.md
src/brogue/Items.c

Disable auto-targeting when throwing a melee weapon

---

changes/dont-yeet-your-good-potions.md
src/brogue/Items.c

Disable auto-targeting when throwing a good or unknown potion

---

.github/workflows/build.yml
Makefile
src/brogue/Items.c
src/brogue/SeedCatalog.c

Turn off very common formatting issues and fix the remainder

Add -Werror=format-security back

---

src/brogue/Recordings.c

Fix 64-bit seed OOS on load

---

changes/wizard-mode-create-item.md
src/brogue/Globals.c
src/brogue/IO.c
src/brogue/IncludeGlobals.h
src/brogue/Rogue.h
src/brogue/Wizard.c

Any item can be created in wizard mode, with an Easter egg for gold.

Create item or monster in wizard mode

---

src/brogue/Architect.c
src/brogue/IO.c
src/brogue/Items.c
src/brogue/Monsters.c
src/brogue/Movement.c
src/brogue/Rogue.h
src/brogue/RogueMain.c
src/brogue/SeedCatalog.c
src/brogue/Time.c

Updates functions mostly in `Items.c` to make use of the `pos` type for coordinates.

use pos type for item functions

---

src/brogue/MainMenu.c

- "New Game" button moved to the top menu button 
- Removed "Options" flyout
- Renamed mode/variant buttons and moved them to the "Play" flyout

Relocate New Game and some other buttons

---

changes/dungeon-version-1.11.md
src/variants/GlobalsBrogue.c

Dungeon version 1.11

---

src/brogue/SeedCatalog.c

Updated instructions for playing a seeded game

Update seed catalog message

---

BUILD.md
make/brogue.mk

Fix MSYS2 build instructions

---

src/brogue/IO.c
src/brogue/Items.c
src/brogue/Rogue.h
src/brogue/Time.c

This refactor should make issues like #614 easier to implement.

Refactor the apply function

---

changes/feats.md
src/brogue/Combat.c
src/brogue/Globals.c
src/brogue/Globals.h
src/brogue/IO.c
src/brogue/Items.c
src/brogue/Recordings.c
src/brogue/Rogue.h
src/brogue/RogueMain.c
src/brogue/Time.c
src/variants/GlobalsBrogue.c
src/variants/GlobalsRapidBrogue.c

This is an initial rework of feats. I'd like to add rewards next but that requires changing the end game screens so I decided to save it for later.

Rework feats and add feats screen

---

changes/prevent-items-drifting-through-walls.md
src/brogue/Items.c

Fixes #619. Related to #661.
I think it's a reasonable fix to a rare situation.

Fix items drifting through walls

---

changes/negate-inanimates.md
src/brogue/IO.c
src/brogue/Items.c

Fix messaging and sidebar when negating inanimates

---

changes/monster-always-reflects.md
src/brogue/Globals.c
src/brogue/Items.c
src/brogue/Monsters.c
src/brogue/Rogue.h

I tried adding a behavior flag (bit 31) first but the compiler complained... something about int.

Add ability and description for monsters that always reflect
